spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/home/mhc/Documents/DpNote/src/main/resources/todo.sqlite
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect