spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/todo.sqlite
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql